export const FIREBASE_LIST_FETCH = 'FIREBASE_LIST_FETCH';
export const FIREBASE_LIST_ITEM_FETCH = 'FIREBASE_LIST_ITEM_FETCH';
export const FIREBASE_LIST_ADD_ITEM = 'FIREBASE_LIST_ADD_ITEM';
export const FIREBASE_LIST_ADD = 'FIREBASE_LIST_ADD';
export const FIREBASE_LIST_DELETE_FETCH = 'FIREBASE_LIST_DELETE_FETCH';
export const FIREBASE_LIST_DELETE = 'FIREBASE_LIST_DELETE';
